// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mocidade015.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mocidade015.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mocidade015.Models.Acompanhante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("RgCpf")
                        .HasColumnType("text")
                        .HasColumnName("rgcpf");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioResponsavelId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuarioresponsavelid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioResponsavelId");

                    b.ToTable("Acompanhantes", (string)null);
                });

            modelBuilder.Entity("Mocidade015.Models.Assento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<bool>("Ocupado")
                        .HasColumnType("boolean")
                        .HasColumnName("ocupado");

                    b.Property<Guid>("OnibusId")
                        .HasColumnType("uuid")
                        .HasColumnName("onibusid");

                    b.HasKey("Id");

                    b.HasIndex("OnibusId", "Numero")
                        .IsUnique();

                    b.ToTable("Assentos", (string)null);
                });

            modelBuilder.Entity("Mocidade015.Models.ListaEspera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datasolicitacao");

                    b.Property<string>("TerminalDesejado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("terminaldesejado");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ListaEspera", (string)null);
                });

            modelBuilder.Entity("Mocidade015.Models.Onibus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataViagem")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dataviagem");

                    b.Property<TimeSpan>("HorarioSaida")
                        .HasColumnType("interval")
                        .HasColumnName("horariosaida");

                    b.Property<int>("LotacaoMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("lotacaomaxima");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("TerminalSaida")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("terminalsaida");

                    b.HasKey("Id");

                    b.ToTable("Onibus", (string)null);
                });

            modelBuilder.Entity("Mocidade015.Models.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcompanhanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("acompanhanteid");

                    b.Property<Guid>("AssentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("assentoid");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datareserva");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuarioid");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("AcompanhanteId");

                    b.HasIndex("AssentoId")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas", (string)null);
                });

            modelBuilder.Entity("Mocidade015.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datacriacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Rg")
                        .HasColumnType("text")
                        .HasColumnName("rg");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senhahash");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Mocidade015.Models.Acompanhante", b =>
                {
                    b.HasOne("Mocidade015.Models.Usuario", "UsuarioResponsavel")
                        .WithMany("Acompanhantes")
                        .HasForeignKey("UsuarioResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioResponsavel");
                });

            modelBuilder.Entity("Mocidade015.Models.Assento", b =>
                {
                    b.HasOne("Mocidade015.Models.Onibus", "Onibus")
                        .WithMany("Assentos")
                        .HasForeignKey("OnibusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Onibus");
                });

            modelBuilder.Entity("Mocidade015.Models.ListaEspera", b =>
                {
                    b.HasOne("Mocidade015.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Mocidade015.Models.Reserva", b =>
                {
                    b.HasOne("Mocidade015.Models.Acompanhante", "Acompanhante")
                        .WithMany()
                        .HasForeignKey("AcompanhanteId");

                    b.HasOne("Mocidade015.Models.Assento", "Assento")
                        .WithMany()
                        .HasForeignKey("AssentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mocidade015.Models.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acompanhante");

                    b.Navigation("Assento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Mocidade015.Models.Onibus", b =>
                {
                    b.Navigation("Assentos");
                });

            modelBuilder.Entity("Mocidade015.Models.Usuario", b =>
                {
                    b.Navigation("Acompanhantes");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
