name: Deploy Automático para AWS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Puxar o código do repositório
      uses: actions/checkout@v4

    - name: 2. Configurar o ambiente .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: 3. Publicar o projeto (Build)
      run: dotnet publish Mocidade015/Mocidade015.csproj -c Release -r linux-x64 --self-contained false -o ./publish

    - name: 4. PARAR o serviço (Desbloquear arquivos)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo systemctl stop vinnisantos.service
          sudo mkdir -p /var/www/vinnisantos
          sudo chown -R ubuntu:ubuntu /var/www/vinnisantos

    - name: 5. Enviar os arquivos novos (SCP)
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "publish"
        target: "/var/www/vinnisantos"
        strip_components: 1

    - name: 6. INICIAR o serviço novamente
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo systemctl start vinnisantos.service
